#!name= CamScanner Pro
#!desc= Quocchien
# Shadowrocket: 2025-12-21 18:48:00
# Bản Quyền Thuộc Về Quốc Chiến ❤️‍🩹
# Tham Gia Nhóm Telegram: https://t.me/shadowrocketunlockproapps

[Mitm]
hostname =%APPEND% ap*.intsig.net

[Script]
扫描全能王=type=http-response,pattern=https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?,requires-body=1, script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/CamScanner.js
